### ISSUE TITLE
help

### ISSUE THREAD

**Issue by twiztidloc** [JagSwag2014/OnTheClock-Spigot#3]
installed it on my server and dont seem to be working

**Comment by JagSwag2014** [comment]
Sorry you're having trouble. What version of Minecraft and OnTheClock are you using? Also, could you provide server logs? Thanks!

**Comment by twiztidloc** [comment]
server logs aint poping up with error just noone is seeing the otcs upon login im using the latest i could find on spigot and 1.11

**Comment by JagSwag2014** [comment]
Make sure the player you want to have the login message has the permissions "otc.clock" AND "otc.announce.mod". If you're wanting the player to have the ability to set their own custom join message, they need those two permissions and "otc.announce.custom".

**Comment by twiztidloc** [comment]
still not working etting errors now ver] WARN at java.lang.Thread.run(Unknown Source)
29.03 20:36:23 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
29.03 20:36:23 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
29.03 20:36:23 [Server] WARN at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
29.03 20:36:23 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
29.03 20:36:23 [Server] WARN at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
29.03 20:36:23 [Server] WARN at java.util.concurrent.FutureTask.run(Unknown Source)
29.03 20:36:23 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
29.03 20:36:23 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
29.03 20:36:23 [Server] WARN at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
29.03 20:36:23 [Server] WARN at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
29.03 20:36:23 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1180)
29.03 20:36:23 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1345)
29.03 20:36:23 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
29.03 20:36:23 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
29.03 20:36:23 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
29.03 20:36:23 [Server] WARN at com.mythton.otc.Commands.OTCCommand.onCommand(OTCCommand.java:79)
29.03 20:36:23 [Server] WARN at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128)
29.03 20:36:23 [Server] WARN at java.io.FileInputStream.&lt;init&gt;(Unknown Source)
29.03 20:36:23 [Server] WARN at java.io.FileInputStream.open(Unknown Source)
29.03 20:36:23 [Server] WARN at java.io.FileInputStream.open0(Native Method)
29.03 20:36:23 [Server] WARN java.io.FileNotFoundException: plugins/OnTheClock/Players/f7bd0bb1-ca19-4209-a267-053ca72477c9.clock (No such file or directory)

**Comment by JagSwag2014** [comment]
It seems your issue is that the player file was not generated. This file is created upon joining the server if you have the "otc.clock" permission. I'm thinking you joined, added permissions, and then tried to set your custom join message. This wouldn't work, though, since the file is created upon join. So, if you have the correct permissions, leaving and rejoining should fix the problem. If not, try restarting the server. 

I will add a workaround for this in the future. Thanks for reporting, and let me know if there's still a problem.
